# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 孤独狂饮
subtitle: 只要有百分之一的梦想，就要付出百分之百的努力。努力不一定成功，但是不努力就一定不会成功！
description: 创建这个博客的目的是为了提炼技术能力。已经在Android 领域 四年多了，虽说写过一些博客，但是基本都是杂乱的，偶尔才能出一两篇精华。但是精华因为杂碎的覆盖，不能凸显其价值，因此该博客就是了存储一些有价值的东西而存在!
author: gdky005 #作者名字
language: zh-Hans #语言 中国大陆简体中文的标准语系地区码是zh-CN 台灣是正體中文zh-TW, Next zh-Hans; #http://theme-next.iissnan.com/getting-started.html
timezone: PRC #设置为中华人民共和国

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://gdky005.com #博客地址
root: / #博客根目录
permalink: :year/:month/:day/:title/ #博客url地址结构 
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
# archive: 0 #设置为1 是全部展示
# category: 2
# tag: 2

# Server
# port: 4000 #本地服务器端口是4000
# server_ip: localhost #本地服务器地址
# logger: false
# logger_format: dev

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next #主题设置
stylus:
  compress: true

# 订阅
feed:
  type: atom
  path: atom.xml
  limit: 5
  hub:
# 生成 sitemap
sitemap:
    path: sitemap.xml
# 添加百度统计
baidu_analytics: 60604cb7585e80203a90adfb670d42bc
# 多说分享服务
duoshuo_share: true
duoshuo_hotartical: true
# hexo-generator-search
search:
  path: search.xml
  field: post

# # Deployment
# ## Docs: http://hexo.io/docs/deployment.html
# deploy:
#   type: git #部署类型, 本文使用Github
#   repository: https://github.com/gdky005/gdky005-Blog.git
# branch: gh-pages

# Deployment 部署配置
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:gdky005/gdky005-Blog.git,gh-pages
    coding: git@git.coding.net:gdky005/gdky005-Bolg.git,coding-pages



# type: git
#   repo:
#     github: https://github.com/micklong/micklong.github.io.git,gh-pages
#     coding: https://git.coding.net/micklong/micklong.git,master
# repository: git@github.com:gdky005/gdky005-Blog.git #你的github page 仓库
# branch: gh-pages

backup:
    type: git
    repository:
       github: git@github.com:gdky005/gdky005-Blog.git,backup
       coding: git@git.coding.net:gdky005/gdky005-Bolg.git,backup
